# Generated by Django 3.1.4 on 2020-12-05 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publication_data',
            new_name='publication_date',
        ),
    ]
